### ISSUE TITLE
Numpy array expected to see 1 array(s), but instead got the following list of 2 arrays

### ISSUE THREAD

**Issue by dadelani** [maxfriedrich/deid-training-data#4]
The full error trace after running:
python -m deid.experiment deid_resources/config/generated/config_001.yaml 

File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/aaaa/PycharmProjects/deid-training-data/deid/experiment/__main__.py", line 15, in <module>
    main()
  File "/aaaa/PycharmProjects/deid-training-data/deid/experiment/__main__.py", line 11, in main
    run_experiment(args.config)
  File "/aaaa/PycharmProjects/deid-training-data/deid/experiment/run.py", line 7, in run_experiment
    experiment(config)
  File "/aaaa/PycharmProjects/deid-training-data/deid/experiment/basic.py", line 75, in basic_experiment
    train_and_validate(model, config, tr, embeddings, extra_features, batch_size, test_batch_size, experiment_dir)
  File "/aaaa/PycharmProjects/deid-training-data/deid/experiment/basic.py", line 157, in train_and_validate
    use_multiprocessing=True)
  File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/site-packages/keras/engine/training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/site-packages/keras/engine/training.py", line 1209, in train_on_batch
    class_weight=class_weight)
  File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/site-packages/keras/engine/training.py", line 749, in _standardize_user_data
    exception_prefix='input')
  File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/site-packages/keras/engine/training_utils.py", line 101, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        ...

Also,
python -m deid.experiment deid_resources/config/generated/config_alternating_001.yaml

 File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/aaaa/PycharmProjects/deid-training-data/deid/experiment/__main__.py", line 15, in <module>
    main()
  File "/aaaa/PycharmProjects/deid-training-data/deid/experiment/__main__.py", line 11, in main
    run_experiment(args.config)
  File "/aaaa/PycharmProjects/deid-training-data/deid/experiment/run.py", line 7, in run_experiment
    experiment(config)
  File "/aaaa/PycharmProjects/deid-training-data/deid/experiment/alternating.py", line 131, in alternating_experiment
    **config['model_args'])
  File "/aaaa/PycharmProjects/deid-training-data/deid/model/adversarial.py", line 102, in __init__
    adversary_output = concatenate(adversary_outputs, axis=-1)
  File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/site-packages/keras/layers/merge.py", line 641, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/aaaa/didelani/anaconda3/envs/deid-training-data/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/aaaa/anaconda3/envs/deid-training-data/lib/python3.6/site-packages/keras/layers/merge.py", line 341, in build
    raise ValueError('A `Concatenate` layer should be called '
ValueError: A `Concatenate` layer should be called on a list of at least 2 inputs

**Comment by maxfriedrich** [comment]
Thanks again! 

The first problem occurs because the experiment script, by mistake, feeds the model some "extra features" in addition to the embeddings (which I implemented to support the [casing feature](https://github.com/maxfriedrich/deid-training-data/blob/ee28bee4a02f912e3664bb7aff1717318f4f4df9/deid/data/feature.py#L24)) which the model is not expecting. I'll try to prepare a fix later! In the meantime, you can add this to your config to hopefully make the model and experiment code compatible again:

```yaml
...
experiment:
  ...
  extra_features:
    - one # for a useless single constant 1.0 feature, or
    - case # for this casing feature from above
```

**Comment by maxfriedrich** [comment]
If you're not doing so already, I highly recommend you to try the `python -m deid.tools.dataset` tool that creates smaller datasets from the original to check more quickly if everything works, e.g.

```bash
python -m deid.tools.dataset 0.001
```

creates two directories `deid_resources/i2b2_data/generated/train-0.001-datetime` and `deid_resources/i2b2_data/generated/validation-0.001-datetime` using 0.1% of the data (only 1 xml file each) which you can then specify in your config, e.g.

```yaml
...
experiment:
  ...
  train_set: generated/train-0.001-...
  validation_set: generated/validation-0.001-...
```

**Comment by dadelani** [comment]
Okay, thanks for the suggestion. The smaller dataset is quicker to check things out

**Comment by maxfriedrich** [comment]
Ah, I also found a solution for your second problem, it doesn't seem to work with only one adversary. Sorry about that! I pushed a fix just now.

**Comment by dadelani** [comment]
The first problem has been resolved. Trying out the second solution you provided for the second problem

**Comment by dadelani** [comment]
Both issues have been resolved. Thanks for your quick replies

**Comment by KavishBhatia** [comment]
I am getting the same error when trying to execute ``` python -m deid.experiment deid_resources/config/generated/config_001.yaml```

Traceback (most recent call last):
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/8bhatia/deid-training-data/deid/experiment/__main__.py", line 15, in <module>
    main()
  File "/home/8bhatia/deid-training-data/deid/experiment/__main__.py", line 11, in main
    run_experiment(args.config)
  File "/home/8bhatia/deid-training-data/deid/experiment/run.py", line 7, in run_experiment
    experiment(config)
  File "/home/8bhatia/deid-training-data/deid/experiment/basic.py", line 74, in basic_experiment
    train_and_validate(model, config, tr, embeddings, extra_features, batch_size, test_batch_size, experiment_dir)
  File "/home/8bhatia/deid-training-data/deid/experiment/basic.py", line 156, in train_and_validate
    use_multiprocessing=True)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/engine/training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/engine/training.py", line 1209, in train_on_batch
    class_weight=class_weight)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/engine/training.py", line 749, in _standardize_user_data
    exception_prefix='input')
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/engine/training_utils.py", line 101, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.      ...

Also added 
```...
experiment:
  ...
  extra_features:
    - one # for a useless single constant 1.0 feature, or
    - case # for this casing feature from above
``` 

to my config file but still got the same error.
