### ISSUE TITLE
 Numpy array expected to see 1 array(s), but instead got the following list of 2 arrays

### ISSUE THREAD

**Issue by KavishBhatia** [maxfriedrich/deid-training-data#5]
I am getting the same error when trying to execute ``` python -m deid.experiment deid_resources/config/generated/config_001.yaml```

Traceback (most recent call last):
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/8bhatia/deid-training-data/deid/experiment/__main__.py", line 15, in <module>
    main()
  File "/home/8bhatia/deid-training-data/deid/experiment/__main__.py", line 11, in main
    run_experiment(args.config)
  File "/home/8bhatia/deid-training-data/deid/experiment/run.py", line 7, in run_experiment
    experiment(config)
  File "/home/8bhatia/deid-training-data/deid/experiment/basic.py", line 74, in basic_experiment
    train_and_validate(model, config, tr, embeddings, extra_features, batch_size, test_batch_size, experiment_dir)
  File "/home/8bhatia/deid-training-data/deid/experiment/basic.py", line 156, in train_and_validate
    use_multiprocessing=True)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/engine/training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/engine/training.py", line 1209, in train_on_batch
    class_weight=class_weight)
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/engine/training.py", line 749, in _standardize_user_data
    exception_prefix='input')
  File "/home/8bhatia/anaconda3/envs/deid_env/lib/python3.6/site-packages/keras/engine/training_utils.py", line 101, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.      ...

Also added 
```...
experiment:
  ...
  extra_features:
    - one # for a useless single constant 1.0 feature, or
    - case # for this casing feature from above
``` 

to my config file but still got the same error.

_Originally posted by @KavishBhatia in https://github.com/maxfriedrich/deid-training-data/issues/4#issuecomment-698244814_

**Comment by maxfriedrich** [comment]
Problem was solved?

**Comment by KavishBhatia** [comment]
Yes

Thank You
